import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO
// nav가 포함된 헤더 만들기
// 골격부터 반응형이 가능하도록 만들기
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sans.className}>
      <body className="flex flex-col w-full max-w-screen-2xl mx-auto">
        <Header />
        <main className="grow bg-slate-300">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
