import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Posts",
  description: "Generated by jamanan",
};

export default function PostsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="flex flex-col">
      {/* TODO: 컴포넌트 분리하기 */}
      <nav className="flex items-center justify-between py-10">
        <button className="py-4 flex-1 font-semibold hover:opacity-70">
          All
        </button>
        <button className="py-4 flex-1 font-semibold hover:opacity-70">
          Ilsang
        </button>
        <button className="py-4 flex-1 font-semibold hover:opacity-70">
          Tips
        </button>
        <button className="py-4 flex-1 font-semibold hover:opacity-70">
          Next
        </button>
      </nav>
      <div>{children}</div>
    </section>
  );
}
